### ISSUE TITLE
How do I train dynamic value based commands

### ISSUE THREAD

**Issue by kondareddy** [nhannt201/VoiceNET.Library#12]
I am been looking dynamic command but found lot of samples with hard coded commands only. below is my requirement.

few commands

call {x} - x will be dynamic value - name of the user
schedule meeting at {y} - y dynamic value like 11:30 AM
launch {z} - z dynamic value like MS Teams, Excel
Please help me how I can build app listing these commands.

**Comment by nhannt201** [comment]
Sorry, your topic is out of the scope of the project, and I would like to close the discussion here.
