### ISSUE TITLE
MLModel corrupt

### ISSUE THREAD

**Issue by SwartBergStudio** [nhannt201/VoiceNET.Library#13]
The code MLModel.zip used to showcase the application is corrupt

**Comment by nhannt201** [comment]
This is just a sample model and has a lot of limitations regarding language.
You can create your own model using the provided tool: https://github.com/nhannt201/VoiceNET.Library/tree/main/VoiceNET.Lib.MicBuilder

**Comment by nhannt201** [comment]
@Mecerburn If you still need to use the sample MLModel.zip file to run the program demo, you can download it here:
 
https://www.mediafire.com/file/ebucf491r8vui5d/MLModel.zip/file

I apologize for the inconvenience caused by the limited upload file size.
