### ISSUE TITLE
MicBuilder error

### ISSUE THREAD

**Issue by huthido** [nhannt201/VoiceNET.Library#14]
NAudio.MmException
  HResult=0x80131500
  Message=UnspecifiedError calling mixerSetControlDetails
  Source=NAudio.WinMM
  StackTrace:
   at NAudio.Mixer.UnsignedMixerControl.set_Value(UInt32 value)
   at VoiceNET.Lib.MicBuilder.frmMicBuilder..ctor() in ...VoiceNET\VoiceNET.Lib.MicBuilder\frmMicBuilder.cs:line 19
   at VoiceNET.Lib.MicBuilder.Program.Main() in D:\DotNet\VoiceNET\VoiceNET.Lib.MicBuilder\Program.cs:line 19

**Comment by nhannt201** [comment]
Can you describe the situation in which this error occurs? I need to know the details of the error's source to better assist you.

If you are using the new version of NAudio, please downgrade or use the version that is used in the VoiceNET Library.

**Comment by nhannt201** [comment]
This error message appears when I am calling the "mixerSetControlDetails" function in the NAudio.WinMM library. According to the error message, there is an unspecified issue when calling this function, which may be related to improperly setting audio mixer control details.

Following the stack trace, I see that the error is occurring in the constructor of the "frmMicBuilder" class in the "VoiceNET.Lib.MicBuilder" namespace.

However, without specific information about the particular circumstances that are causing this error, I cannot provide a more detailed solution. Nonetheless, some possible causes of this error could include incorrect audio device settings, issues with audio drivers or hardware, or conflicts with other audio software running on the system.

One possible solution is to check your audio device settings and ensure that your audio drivers are up to date. Additionally, you may want to try closing other audio software that is running on your system to see if that resolves the issue.
