### ISSUE TITLE
Further development

### ISSUE THREAD

**Issue by ToGoOrNotToGo** [nhannt201/VoiceNET.Library#15]
This is a very interesting library. Thanks!
Will there be an update, a further development?

**Comment by nhannt201** [comment]
Thank you for expressing your interest in this library. In the future, I may reconsider whether to continue developing this project. However, at the moment, I do not have any immediate plans to continue its development. Please note that the project is currently on hold.

**Comment by ToGoOrNotToGo** [comment]
The most important/interesting thing would be an ML.NET update. There are breaking changes in image classification. Can you please update to the newest ML.NET?
